// Activity feed data — mirrors the content from the user's screenshots,
// re-organized into a cleaner timeline.

window.SPARK_DATA = {
  sessionTitle: "Session — Wed 24 May",
  sessionContext: "Personal workspace · Gmail, Drive, Local",
  activity: [
    {
      id: "u1",
      kind: "user",
      time: "07:45 PM",
      text: "hey there",
    },
    {
      id: "a1",
      kind: "assistant",
      time: "07:45 PM",
      tone: "softly",
      text: "Hey, sir. What's on your mind?",
      suggestions: ["Inbox", "File Search", "Drive", "Location"],
    },

    {
      id: "u2",
      kind: "user",
      time: "07:46 PM",
      text: "check is there any email and also check is there any files in my google drive",
    },
    {
      id: "a2",
      kind: "assistant",
      time: "07:46 PM",
      tone: "focused",
      text: "Checking email and Drive files now.",
      tools: [
        {
          name: "Inbox",
          icon: "mail",
          status: "ok",
          duration: "11.3s",
          summary: "20 emails fetched from Gmail",
          steps: [
            "Connecting to Gmail",
            "Fetching inbox",
            "Reading 20 emails",
          ],
          preview: {
            kind: "emails",
            items: [
              { from: "Nikita Adhakira", subject: "COUPLES, KEEP YOUR SOCIAL ACCOUNTS TO YOURSELF", time: "2h", flag: "promo" },
              { from: "Vercel", subject: "Your deployment is ready · spark-web-app", time: "4h", flag: "build" },
              { from: "GitHub", subject: "[PR #214] Refactor activity timeline", time: "6h", flag: "code" },
              { from: "Linear", subject: "SPK-118 marked as Done — Tool result cards", time: "9h", flag: "task" },
            ],
            more: 16,
          },
        },
        {
          name: "File Search",
          icon: "drive",
          status: "ok",
          duration: "10.9s",
          summary: "5 files found in Google Drive",
          preview: {
            kind: "files",
            items: [
              { name: "project report.docx", size: "248 KB", time: "Today" },
              { name: "meeting notes.pdf", size: "1.2 MB", time: "Yesterday" },
              { name: "budget spreadsheet.xlsx", size: "84 KB", time: "Mon" },
              { name: "contract agreement.doc", size: "92 KB", time: "12 May" },
              { name: "presentation slides.pptx", size: "5.4 MB", time: "08 May" },
            ],
          },
        },
      ],
    },

    {
      id: "u3",
      kind: "user",
      time: "05:24 PM",
      text: "Take the screenshot and open the screenshot directory.",
    },
    {
      id: "a3",
      kind: "assistant",
      time: "05:24 PM",
      tone: "calmly",
      text: "Opening the screenshot directory.",
      tools: [
        {
          name: "Screenshot",
          icon: "camera",
          status: "ok",
          duration: "5.4s",
          summary: "Screenshot saved",
          note: "Recovered after 2 retries",
          steps: [
            "Capturing screenshot",
            "Recovered after 2 retry(s)",
            "Saved to ~/Pictures/Screenshots",
          ],
        },
        {
          name: "App",
          icon: "folder",
          status: "ok",
          duration: "4.3s",
          summary: "Opened C:\\Users\\Aanand\\OneDrive\\Pictures",
          steps: ["Resolving path", "Launching shell", "Opened"],
        },
      ],
    },

    {
      id: "u4",
      kind: "user",
      time: "05:49 PM",
      text: "search the hospitals near me",
    },
    {
      id: "a4",
      kind: "assistant",
      time: "05:49 PM",
      tone: "calmly",
      text: "Finding nearby hospitals now.",
      tools: [
        {
          name: "Location",
          icon: "pin",
          status: "ok",
          duration: "164ms",
          summary: "Kathmandu, Bagmati Province",
        },
        {
          name: "Research",
          icon: "search",
          status: "ok",
          duration: "15.0s",
          summary: "3 results · Kathmandu Model Hospital, Metro Kathmandu Hospital, Nepal Mediciti",
        },
      ],
      result: {
        kind: "local-service",
        title: "Hospitals near you",
        count: 3,
        items: [
          {
            rank: 1,
            name: "Kathmandu Model Hospital",
            type: "Multi-specialty · Public",
            address: "Pradarshani Marg, Kathmandu",
            distance: "1.2 km",
            rating: 4.3,
            reviews: 1284,
            open: true,
            hours: "24 hours",
            phone: "+977-1-4240805",
            specialties: ["Emergency", "Cardiology", "Pediatrics"],
            tone: "warm",
          },
          {
            rank: 2,
            name: "Metro Kathmandu Hospital",
            type: "Private · Multi-specialty",
            address: "Narayan Gopal Chowk, Maharajgunj, Kathmandu",
            distance: "3.8 km",
            rating: 4.1,
            reviews: 642,
            open: true,
            hours: "24 hours",
            phone: "+977-1-4721111",
            specialties: ["ICU", "Orthopedics"],
            tone: "cool",
          },
          {
            rank: 3,
            name: "Nepal Mediciti",
            type: "Private · Tertiary care",
            address: "Bhaisepati, Lalitpur · Kathmandu",
            distance: "8.4 km",
            rating: 4.5,
            reviews: 2103,
            open: true,
            hours: "24 hours",
            phone: "+977-1-4217766",
            specialties: ["Oncology", "Neuro", "Transplant"],
            tone: "mauve",
          },
        ],
      },
    },

    {
      id: "u5",
      kind: "user",
      time: "07:50 PM",
      text: "tell me what are the files present in the google drive",
    },
    {
      id: "a5",
      kind: "assistant",
      time: "07:50 PM",
      tone: "calmly",
      text: "I've got the list, sir: project report.docx, meeting notes.pdf, budget spreadsheet.xlsx, contract agreement.doc, and presentation slides.pptx.",
      tools: [
        {
          name: "Shell",
          icon: "terminal",
          status: "err",
          duration: "0.4s",
          summary: "shell_execute returned unsuccessful output",
          error: "Exit 127 — bindings could not resolve dependency: step_1",
          retryable: true,
        },
      ],
    },
  ],
};
