# AUTO-GENERATED — do not edit by hand.
# Regenerate with: python -m scripts.tool_tester --gen-stubs
from typing import Any, Dict

ToolResult = Dict[str, Any]

class _ToolsProxy:
    async def agent_status(self) -> ToolResult:
        """Get current status of the agent"""
        ...
    async def ai_summarize(self, context: str, query: str = ..., mode: str = 'tts', max_length: int = 700) -> ToolResult:
        """Summarize AI-related content like logs, conversations, or documents"""
        ...
    async def app_close(self, target: str, force: bool = False) -> ToolResult:
        """Kill running processes"""
        ...
    async def app_focus(self, target: str) -> ToolResult:
        """Bring application to front and focus"""
        ...
    async def app_maximize(self, target: str) -> ToolResult:
        """Maximize application window"""
        ...
    async def app_minimize(self, target: str) -> ToolResult:
        """Minimize application window"""
        ...
    async def app_open(self, target: str, destination: str = 'auto', web_fallback_policy: str = 'validate_then_ask', args: list = ...) -> ToolResult:
        """Open local applications or websites based on user intent"""
        ...
    async def app_restart(self, target: str, save_state: bool = True) -> ToolResult:
        """Restart apps safely"""
        ...
    async def artifact_list(self, kind: str = ..., tool_name: str = ..., limit: int = 10, latest_only: bool = False) -> ToolResult:
        """List saved artifacts such as screenshots"""
        ...
    async def artifact_open(self, artifact_id: str = ..., kind: str = ..., latest: bool = True, app: str = ...) -> ToolResult:
        """Directly open a saved artifact on the current runtime machine"""
        ...
    async def artifact_resolve(self, artifact_id: str = ..., kind: str = ..., latest: bool = True) -> ToolResult:
        """Resolve a saved artifact to a local path and viewer hints"""
        ...
    async def battery_status(self) -> ToolResult:
        """Power monitoring and battery info"""
        ...
    async def brightness_decrease(self, amount: int = 1) -> ToolResult:
        """Decrease screen brightness by specified amount (default -1)"""
        ...
    async def brightness_increase(self, amount: int = 1) -> ToolResult:
        """Increase screen brightness by specified amount (default +1)"""
        ...
    async def brightness_status(self) -> ToolResult:
        """Get current screen brightness level"""
        ...
    async def call_audio(self, contact: str, platform: str = 'auto') -> ToolResult:
        """Start an audio call with a contact"""
        ...
    async def call_video(self, contact: str, platform: str = 'auto') -> ToolResult:
        """Start a video call with a contact"""
        ...
    async def clipboard_read(self) -> ToolResult:
        """Read clipboard content"""
        ...
    async def clipboard_write(self, content: str) -> ToolResult:
        """Write to clipboard"""
        ...
    async def current_location(self, detailed: bool = False) -> ToolResult:
        """Get current location via IP geolocation"""
        ...
    async def email_delete(self, message_id: str, user_id: str) -> ToolResult:
        """Permanently delete an email — IRREVERSIBLE. Use email_trash for a safer alternative"""
        ...
    async def email_label(self, message_id: str, user_id: str, add_labels: list = [], remove_labels: list = []) -> ToolResult:
        """Add or remove labels on a single email (supports system labels like STARRED, IMPORTANT and custom ones)"""
        ...
    async def email_labels_list(self, user_id: str) -> ToolResult:
        """List all Gmail labels (system + user-created) with unread counts"""
        ...
    async def email_list(self, user_id: str, label_ids: list = ['INBOX'], query: str = '', max_results: int = 20) -> ToolResult:
        """List emails from the mailbox with optional label and query filters"""
        ...
    async def email_mark_read(self, message_ids: list, user_id: str) -> ToolResult:
        """Mark one or more emails as read"""
        ...
    async def email_mark_unread(self, message_ids: list, user_id: str) -> ToolResult:
        """Mark one or more emails as unread"""
        ...
    async def email_move(self, message_id: str, destination: str, user_id: str, remove_from: list = ['INBOX']) -> ToolResult:
        """Move an email to a different label/folder by adding the destination label and removing source labels"""
        ...
    async def email_organize(self, query: str, action: str, user_id: str, max_messages: int = 50) -> ToolResult:
        """Bulk-organize emails matching a search query. Actions: mark_read | mark_unread | archive | trash | label:<name> | unlabel:<name>"""
        ...
    async def email_read(self, message_id: str, user_id: str) -> ToolResult:
        """Fetch the full content (headers, body, attachments) of a single email by ID"""
        ...
    async def email_reply(self, message_id: str, body: str, user_id: str, to: str = ..., subject: str = ...) -> ToolResult:
        """Reply to an existing email within the same thread"""
        ...
    async def email_search(self, query: str, user_id: str, max_results: int = 20) -> ToolResult:
        """Search emails using full Gmail search syntax"""
        ...
    async def email_send(self, to: str, subject: str, body: str, user_id: str, cc: str = '', bcc: str = '') -> ToolResult:
        """Compose and send a new email"""
        ...
    async def email_trash(self, message_id: str, user_id: str) -> ToolResult:
        """Move an email to Trash (recoverable within 30 days)"""
        ...
    async def file_copy(self, source: str, destination: str, overwrite: bool = False) -> ToolResult:
        """Copy files"""
        ...
    async def file_create(self, path: str, content: str = '', overwrite: bool = False) -> ToolResult:
        """Create new files with content"""
        ...
    async def file_delete(self, path: str, permanent: bool = False) -> ToolResult:
        """Safely delete files"""
        ...
    async def file_move(self, source: str, destination: str, overwrite: bool = False) -> ToolResult:
        """Move files to new location"""
        ...
    async def file_open(self, path: str, app: str = ...) -> ToolResult:
        """Open files with default or specified app"""
        ...
    async def file_read(self, path: str) -> ToolResult:
        """Read content from a file"""
        ...
    async def file_search(self, query: str, path: str = '.', max_results: int = 50) -> ToolResult:
        """Locate files and folders"""
        ...
    async def folder_cleanup(self, path: str, action: str) -> ToolResult:
        """Organize and clean folders"""
        ...
    async def folder_create(self, path: str, title: str = '', recursive: bool = True) -> ToolResult:
        """Create new directories"""
        ...
    async def folder_organize(self, path: str) -> ToolResult:
        """Organize folder structure"""
        ...
    async def gmail_read(self, query: str = ..., max_results: int = 10) -> ToolResult:
        """Read/list emails via the external action bridge with rate limiting and audit logging"""
        ...
    async def gmail_send(self, to: str, subject: str, body: str) -> ToolResult:
        """Send an email via the external action bridge with rate limiting and audit logging"""
        ...
    async def lock_screen(self, delay_seconds: int = 0) -> ToolResult:
        """Lock the OS screen immediately"""
        ...
    async def message_file(self, contact: str, file_path: str, caption: str = '', platform: str = 'auto') -> ToolResult:
        """Send a document or file (PDF, ZIP, DOCX, etc.) to a contact"""
        ...
    async def message_media(self, contact: str, media_path: str, caption: str = '', platform: str = 'auto') -> ToolResult:
        """Send a photo or video to a contact"""
        ...
    async def message_send(self, contact: str, message: str, platform: str = 'auto') -> ToolResult:
        """Send a text message to a contact"""
        ...
    async def mic_mute(self) -> ToolResult:
        """Mute the microphone on the connected desktop client"""
        ...
    async def mic_unmute(self) -> ToolResult:
        """Unmute the microphone on the connected desktop client"""
        ...
    async def music_pause(self, session_id: str = 'default') -> ToolResult:
        """Pause an active playback session by suspending the player process. Audio stops immediately; position is preserved. Resume with music_resume."""
        ...
    async def music_play(self, title: str, artist: str = ..., album: str = ..., source: str = 'youtube', file_path: str = ..., session_id: str = 'default') -> ToolResult:
        """Play music immediately — streams YouTube/SoundCloud via mpv+yt-dlp with no browser, or plays a local audio file. Audio starts in the background automatically."""
        ...
    async def music_resume(self, session_id: str = 'default') -> ToolResult:
        """Resume a paused playback session. Accumulated pause time is tracked so progress remains accurate."""
        ...
    async def music_status(self, session_id: str = ..., include_system: bool = True) -> ToolResult:
        """Two-layer audio status: (1) our tracked sessions with full metadata, (2) OS-level scan of every process emitting audio via pactl / CoreAudio / WASAPI."""
        ...
    async def music_stop(self, session_id: str = 'default', force: bool = False, stop_all: bool = False) -> ToolResult:
        """Stop one or all active music sessions launched by music_play."""
        ...
    async def network_status(self, check_internet: bool = True) -> ToolResult:
        """Internet connectivity and IP info"""
        ...
    async def notification_push(self, title: str, message: str, urgency: str = 'normal') -> ToolResult:
        """Send native OS notifications"""
        ...
    async def schedule_task(self, label: str, schedule: str, task_plan: list = ...) -> ToolResult:
        """Schedule a recurring task with a cron expression or natural language schedule"""
        ...
    async def screenshot_capture(self, target: str = 'full', save_path: str = ...) -> ToolResult:
        """Capture screen or window"""
        ...
    async def set_reminder(self, label: str, trigger_at: str, notification_text: str = ...) -> ToolResult:
        """Set a reminder that will notify the user at a specific time"""
        ...
    async def shell_agent(self, goal: str, working_dir: str = ..., max_steps: int = 6, allow_network: bool = False) -> ToolResult:
        """Run guarded PowerShell or shell steps with LLM guidance until the task is finished"""
        ...
    async def shell_execute(self, command: str, working_dir: str = ..., timeout_s: float = 30) -> ToolResult:
        """Execute a single shell command on the host system"""
        ...
    async def sound_decrease(self, amount: int = 30) -> ToolResult:
        """Decrease system volume by specified amount (default -30)"""
        ...
    async def sound_increase(self, amount: int = 30) -> ToolResult:
        """Increase system volume by specified amount (default +30)"""
        ...
    async def sound_status(self) -> ToolResult:
        """Get current system volume level and mute status"""
        ...
    async def system_info(self, metrics: list = ['cpu', 'ram', 'disk']) -> ToolResult:
        """Get CPU, RAM, Disk usage"""
        ...
    async def tool_catalog(self, tool_name: str = ..., category: str = ..., execution_target: str = ..., view: str = 'summary', include_examples: bool = True) -> ToolResult:
        """Inspect the canonical tool catalog, schemas, and examples"""
        ...
    async def weather_current(self, lat: float = ..., lon: float = ..., units: str = 'metric') -> ToolResult:
        """Get current weather conditions at user location"""
        ...
    async def weather_forecast(self, lat: float = ..., lon: float = ..., days: int = 7, units: str = 'metric') -> ToolResult:
        """Get a multi-day weather forecast at user location"""
        ...
    async def web_research(self, query: str, mode: str = 'research', max_results: int = 3, max_chars: int = 5000) -> ToolResult:
        """Performs deep web research by searching, scraping top results, and summarizing the findings."""
        ...
    async def web_scrape(self, base_links: list, query: str = ..., max_results: int = 10) -> ToolResult:
        """Fetches and extracts readable content from a public webpage"""
        ...
    async def web_search(self, query: str, max_results: int = 10) -> ToolResult:
        """Search the web for information"""
        ...

tools: _ToolsProxy
